// front-end/src/app/components/tables/materials-table/materials-table.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { MaterialResponseAll, MaterialBase } from '../../../models/material.model';
import { MaterialServiceService } from '../../../services/material.service.service';
import { Observable } from 'rxjs';
import { AsyncPipe } from '@angular/common';

@Component({
  selector: 'app-materials-table',
  standalone: true,
  imports: [AsyncPipe],
  templateUrl: './materials-table.component.html',
  styleUrl: './materials-table.component.css'
})
export class MaterialsTableComponent implements OnInit {
  
  materialsResponse$!: Observable<MaterialResponseAll>;
  
  private materialService = inject(MaterialServiceService);
  
  ngOnInit(): void {
    this.materialsResponse$ = this.materialService.getAllMaterials();
  }
}

<section class="py-12 bg-[#faf9f5] mx-auto">
  <div class="container mx-auto px-6 lg:px-12">
    <h2 class="text-3xl md:text-4xl font-bold text-center text-gray-800 mb-8">
      Materiales <span class="text-blue-600">disponibles</span>
    </h2>
    
    @if (materialsResponse$ | async; as response) {
      <div class="overflow-x-auto mx-auto">
        <table class="min-w-full bg-white rounded-xl shadow-lg">
          <thead>
            <tr class="bg-blue-50">
              <th class="px-6 py-4 text-left text-sm font-semibold text-gray-700">Nombre</th>
              <th class="px-6 py-4 text-left text-sm font-semibold text-gray-700">Descripción</th>
              <th class="px-6 py-4 text-left text-sm font-semibold text-gray-700">Acciones</th>
            </tr>
          </thead>
          <tbody>
            @for (material of response.data.materials; track material.id) {
              <tr class="hover:bg-blue-100 transition duration-200">
                <td class="px-6 py-4 text-gray-800 font-medium">{{ material.name }}</td>
                <td class="px-6 py-4 text-gray-600">{{ material.description }}</td>
               
                <td class="px-6 py-4 flex gap-2 h-full items-center justify-center">
                  <button class="bg-blue-500 hover:bg-blue-600 text-white px-3 py-1 rounded-lg text-xs font-semibold shadow transition duration-200 flex items-center">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536M9 13l6.293-6.293a1 1 0 011.414 0l1.586 1.586a1 1 0 010 1.414L11 17H7v-4z" />
                    </svg>
                    Editar
                  </button>
                  <button class="bg-red-500 hover:bg-red-600 text-white px-3 py-1 rounded-lg text-xs font-semibold shadow transition duration-200 flex items-center">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                    Eliminar
                  </button>
                </td>
              </tr>
            }
            @empty {
              <tr>
                <td colspan="6" class="px-6 py-8 text-center text-gray-500">No hay materiales disponibles</td>
              </tr>
            }
          </tbody>
        </table>
      </div>
    } @else {
      <div class="flex justify-center items-center h-40">
        <div class="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-blue-500"></div>
      </div>
    }
  </div>
</section>

// edgar-fron/src/components/react_components/MaterialsTable.tsx
import React, { useEffect, useState } from 'react';

interface Material {
  id: string;
  name: string;
  description: string;
}

const MaterialsTable: React.FC = () => {
  const [materials, setMaterials] = useState<Material[]>([]);
  const [loading, setLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const fetchMaterials = async () => {
      try {
        const response = await fetch('https://apiedgar.kysedomi.lat/materials/');
        if (!response.ok) {
          throw new Error('Failed to fetch materials');
        }
        const data = await response.json();
        setMaterials(data);
      } catch (err) {
        setError(err instanceof Error ? err.message : 'An error occurred');
      } finally {
        setLoading(false);
      }
    };

    fetchMaterials();
  }, []);

  if (loading) {
    return (
      <div className="overflow-hidden bg-white shadow-md rounded-xl w-full p-6">
        <div className="flex justify-center items-center h-40">
          <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-gray-800"></div>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="overflow-hidden bg-white shadow-md rounded-xl w-full p-6">
        <div className="flex flex-col items-center justify-center space-y-3 h-40 text-red-500">
          <svg xmlns="http://www.w3.org/2000/svg" className="h-10 w-10" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
          </svg>
          <p className="text-lg font-medium">Error: {error}</p>
        </div>
      </div>
    );
  }

  return (
    <div className="overflow-hidden bg-white shadow-md rounded-xl w-full">
      <div className="p-6 border-b border-gray-200 bg-gray-800 text-white flex justify-between">
        <div>
          <h3 className="text-2xl font-bold">
            Materiales <span className="text-blue-300">Disponibles</span>
          </h3>
          <p className="mt-2 text-gray-300">Lista completa de materiales para construcción.</p>
        </div>
        <div>
          <button className="px-4 py-2 bg-blue-300 text-black font-bold rounded-lg hover:bg-blue-400 transition duration-300 flex items-center shadow-sm">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 mr-2" viewBox="0 0 20 20" fill="currentColor">
              <path fillRule="evenodd" d="M10 5a1 1 0 011 1v3h3a1 1 0 110 2h-3v3a1 1 0 11-2 0v-3H6a1 1 0 110-2h3V6a1 1 0 011-1z" clipRule="evenodd" />
            </svg>
            Nuevo Material
          </button>
        </div>
      </div>

      <div className="w-full">
        <table className="w-full divide-y divide-gray-200">
          <thead className="bg-gray-100">
            <tr>
              <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">
                Nombre
              </th>
              <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">
                Descripción
              </th>
              <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">
                Acciones
              </th>
            </tr>
          </thead>
          <tbody className="bg-white divide-y divide-gray-200">
            {materials.length > 0 ? (
              materials.map((material) => (
                <tr key={material.id} className="hover:bg-gray-50 transition-colors">
                  <td className="px-6 py-4 whitespace-nowrap">
                    <div className="text-sm font-medium text-gray-900">{material.name}</div>
                  </td>
                  <td className="px-6 py-4">
                    <div className="text-sm text-gray-500 line-clamp-2">{material.description}</div>
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm">
                    <div className="flex space-x-2">
                      <button className="px-3 py-1.5 bg-gray-800 text-white rounded hover:bg-gray-700 transition-colors">
                        Detalles
                      </button>
                    </div>
                  </td>
                </tr>
              ))
            ) : (
              <tr>
                <td colSpan={3} className="px-6 py-10 text-center text-gray-500">
                  <div className="flex flex-col items-center justify-center space-y-3">
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-10 w-10 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9.172 16.172a4 4 0 015.656 0M9 10h.01M15 10h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                    <p className="text-lg font-medium">No hay materiales disponibles</p>
                  </div>
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>

      {materials.length > 0 && (
        <div className="px-6 py-4 bg-gray-100 border-t border-gray-200 flex items-center justify-between">
          <p className="text-sm text-gray-700">
            <span className="font-medium">{materials.length}</span> materiales en total
          </p>
          <div className="flex space-x-2">
            <button className="px-3 py-1.5 bg-gray-800 text-white border border-gray-800 rounded hover:bg-gray-700 transition-colors">
              Exportar
            </button>
          </div>
        </div>
      )}
    </div>
  );
};

export default MaterialsTable;
